### ISSUE TITLE
Move React to peerDependencies

### ISSUE THREAD

**Issue by bjrmatos** [JakeGinnivan/react-popout#1]
At present when you bundle react-popout with webpack/browserify in my app, **i get two copies of React**, one coming from react-popout and another from my app dependencies.

Moving React to peerDependencies is a good practice in the comunity, see [this](https://github.com/rackt/react-router/blob/master/package.json#L57)

[more info](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375)

maybe 

``` js
"peerDependencies": {
    "react": "0.13.x"
  }
```

is ok :)

**Comment by JakeGinnivan** [comment]
This has been changed and pushed in `0.3.3`
