### ISSUE TITLE
URL?

### ISSUE THREAD

**Issue by vgoklani** [JakeGinnivan/react-popout#11]
Could you please explain what the URL field is doing? I tried moving some components from the main page into a popout, but I keep getting these errors:

Uncaught TypeError: Cannot read property 'style' of undefined

It's not clear to me what needs to be defined in the page of the popoout such that the new component will receive updated props.

**Comment by JakeGinnivan** [comment]
Have added an example of the url field on master.

Could you give me a more complete example which is causing your issue?
