### ISSUE TITLE
Auto-Close the popout window?

### ISSUE THREAD

**Issue by vgoklani** [JakeGinnivan/react-popout#12]
Quick question regarding your online demo. If I open the Popout window, and then close the main window, the Popout window doesn't automatically close. Is there a way to make the Popout window close automatically?  This is the comment from your blog post:

"The nice thing about having this as a React component is that the Popout window’s lifecycle is tied to the lifecycle of the owning component. So when the History component is unmounted the Popout will close the popup it might have had opened."

but how do I make that work in your online example?

**Comment by gf3** [comment]
you could manually close it in an [`beforeunload`](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) handler

**Comment by bigassdragon** [comment]
You can have an 'unbuild' listener close the popout.

**Comment by JakeGinnivan** [comment]
Yeah, componentWillUnmount doesn't actually fire for unloading the page. Have fixed in 19d747f
