### ISSUE TITLE
Popout window doesn't work after *refresh*

### ISSUE THREAD

**Issue by vgoklani** [JakeGinnivan/react-popout#13]
If I go to your demo app:

http://jake.ginnivan.net/react-popout/

click on "pop window out"

then refresh the main tab

and again click on "pop window out", the pop out window no longer displays the timer.

**Comment by thesabbir** [comment]
:+1: ANY SOLUTION ?  @vgoklani ?

**Comment by vgoklani** [comment]
nope - gave up

**Comment by bigassdragon** [comment]
I played around with this for a bit and decided that when the page is refreshing that I would like to close all the popouts. I'd that is something you want then you can add an 'unload' listener that will run the window close function.

If you want it to refresh the page then make the 'unbuild' listener run the update function.

**Comment by JakeGinnivan** [comment]
This will be fixed to close any popups on refresh in next release

**Comment by thesabbir** [comment]
@JakeGinnivan is demo up to date?
