### ISSUE TITLE
dom ready issues in the popout

### ISSUE THREAD

**Issue by KeithWoods** [JakeGinnivan/react-popout#16]
First up nice work on the popout Jake, thanks for the effort.

I was having this odd issues with a popout that hosted a d3 chart, it appears the error was due to  code before the dom was ready in the popout. I then noticed [this line](https://github.com/JakeGinnivan/react-popout/blob/master/lib/react-popout.jsx#L91).

Was there any reason it's called rather than waiting for the window to call it?

Removing this line fixes my problem (in chrome latest).

**Comment by JakeGinnivan** [comment]
Just merged some PR's, don't spose you could try master and let me know. Will be triaging and seeing what issues I can close the do a release soon.

**Comment by KeithWoods** [comment]
I gave the recent PRs an eye over, #7 looks to fix this, however it also looks to introduce some other potential issues. I put some comments on the closed PR for reference. This issue can be closed.
