### ISSUE TITLE
IE 11 broke when popout is already open and content is updated

### ISSUE THREAD

**Issue by fsk1** [JakeGinnivan/react-popout#25]
After first render of popout, while popout window is still open if there is a new trigger of update, getting below error
SCRIPT87: Invalid argument.

If the popout is closed and perform an action that again triggers popout render, starts getting below error for each such render.
SCRIPT5007: Unable to get property 'firstChild' of undefined or null reference

If I close the browser itself and start the session in new browser, same behavior repeats.

This is occurring only in IE 11,but in Chrome it works absolutely fine.

**Comment by vhiroki** [comment]
Regarding the error :

> SCRIPT87: Invalid argument.

I created this issue: https://github.com/facebook/react/issues/9667

It seems to be a problem with ReactDOMRenderer in child windows containers.

**Comment by marchaos** [comment]
Closing this as the listed bug noted by @vhiroki has been fixed.
