### ISSUE TITLE
closeWindow example

### ISSUE THREAD

**Issue by jchabot86** [JakeGinnivan/react-popout#27]
Is there a closeWindow example?  If I put a "ref" on the <Popout> component, it doesn't seem to end up in the this.refs array.

**Comment by marcellodesales** [comment]
The demo shows the correct behavior Opening the component... But with URLs it fails to trigger the method call

**Comment by marchaos** [comment]
I suspect this has been fixed in the latest version. Can you retest?

**Comment by marchaos** [comment]
Duplicate of https://github.com/JakeGinnivan/react-popout/issues/22
