### ISSUE TITLE
blocking for serverside rendering ?

### ISSUE THREAD

**Issue by benbonnet** [JakeGinnivan/react-popout#3]
Not sure if I used correctly, but using react-popout, page is blocked when rendered server side
I had the same problems while using window.location at the wrong place

**Comment by JakeGinnivan** [comment]
Interesting, never thought about the isomorphic side of things.

Not sure why this would happen though, I am using https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount which should only ever fire on the client, not on the server.

The only thing I can think of is `componentDidUpdate`. I don't check if the openedWindow is undefined.

**Comment by benbonnet** [comment]
I might give it another try

**Comment by JakeGinnivan** [comment]
I have added in some checks to stop this component doing anything on SSR. The next release should work for universal apps
