### ISSUE TITLE
Can't hide location options.location = "no", options.location = "0", options.location = 0  

### ISSUE THREAD

**Issue by marcellodesales** [JakeGinnivan/react-popout#37]
None of the option does not work when using the URL. According to the docs you linked:

> NOTE: All features can be set to yes or 1, or just be present to be "on". Set them to no or 0, or in most cases just omit them, to be "off".
> Example: "status=yes", "status=1", and "status" have identical results.

So, how can we specify the options? I can set the size property, but the location is not affected... 

```html
<PopoutWindow url="http://localhost:8080"
            title="Configuration"
            onClosing={this.githubAuthClosed}
            options={{
              height: "780",
              width: "1000",
              toolbar: "no",
              location: "no"
            }}>
          <div />
        </PopoutWindow>
```

**Comment by marchaos** [comment]
You cannot do this in modern browsers - see https://stackoverflow.com/questions/15230137/hide-bar-address-in-popup-chrome
