### ISSUE TITLE
Popout without url property doesn't work after 1.0 release

### ISSUE THREAD

**Issue by limpbrains** [JakeGinnivan/react-popout#39]
An empty page opens without any errors.
If I add an URL - everything works

**Comment by marchaos** [comment]
Hi, let me test that and get back to you.

**Comment by marchaos** [comment]
Hi, I've fixed this issue. I've checked the demos which were broken, but should all be working now. I've published 1.0.1 which should fix this issue. 

Let me know how that goes.

**Comment by marchaos** [comment]
See PR - https://github.com/JakeGinnivan/react-popout/pull/40

**Comment by limpbrains** [comment]
@marchaos fixed, thanks!
