### ISSUE TITLE
isClosing not working

### ISSUE THREAD

**Issue by JD2k** [JakeGinnivan/react-popout#41]
Hello,

isClosing was not working in my project, so i did some debugging.

I think this:

    popoutWindowUnloading() {
        ReactDOM.unmountComponentAtNode(this.state.container);
        this.props.onClosing && this.props.onClosing();
    }

should be changed to this:

    popoutWindowUnloading() {
        if(this.props.onClosing) {
            this.props.onClosing()
        }
        ReactDOM.unmountComponentAtNode(this.state.container);
    }

After the change everything is working fine. 
Thanks for this component, helped me a lot.

**Comment by marchaos** [comment]
Should be fixed in 1.0.3. Re-raise if you have any issues with this.
