### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by alexandrtovmach** [JakeGinnivan/react-popout#55]
> Could not find a declaration file for module 'react-popout'. '/node_modules/react-popout/dist/react-popout.min.js' implicitly has an 'any' type.
> Try `npm install @types/react-popout` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-popout';`

**Comment by adamwdennis** [comment]
Looks like I'm not using this, as there are no typings...

**Comment by marchaos** [comment]
This should be done - types are now included as of version 4.0.0
