### ISSUE TITLE
IE 11 broke when component will update and render at the popout window

### ISSUE THREAD

**Issue by pamelazagatti** [JakeGinnivan/react-popout#9]
After the first render at popout window, when changes some component value or anything that trigger a component update render the UI broke and throw the error infinitely on the IE console.

SCRIPT87: Invalid argument.
"Error: Cannot parse given Error object"
 "Error: Invariant Violation: findComponentRoot(..., .1.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
   at invariant
   at ReactMount.findComponentRoot
   at ReactMount.findReactNodeByID
   at getNode
   at ReactDOMComponent.Mixin._updateDOMProperties
   at ReactDOMComponent.Mixin.updateComponent
}

**Comment by JakeGinnivan** [comment]
I can't reproduce this on master. Could you try and let me know how to reproduce the issue if it's still there
